name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  test:
    name: Test on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run E2E tests
        run: pnpm run test
        env:
          PAT_1: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: "rickstaa"

  code-checks:
    name: Code checks

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Format
        run: pnpm run format:check

      - name: Lint (knip)
        run: pnpm run lint:knip
